### ISSUE TITLE
linebreaks in the hidden tag

### ISSUE THREAD

**Issue by multicode** [gturri/hidden#34]
Hi,

```
<hidden>
The quick brown fox.

Jumps over the lazy dog.
</hidden>
```

If the above code were to be written in dokuwiki, the empty lines are seen erased. It would then appear like..
```
The quick brown fox.
Jumps over the lazy dog.
``` 

I've tried using \\\ inside the hidden tag to insert an empty line, but it didn't work.

Could you please suggest me something ?

Thanks,
Nik

**Comment by gturri** [comment]
As far as I understand, it's  due to the css, because in both cases, each line is going to be in a `p`; but outside the "hidden" tag, a  `p` has by default a positive lower margin, whereas the margin is null inside the "hidden" tag.

You could try to add an additional line break, for example

    <hidden>
    The quick brown fox.
    
    \\
    Jumps over the lazy dog.
    </hidden>

**Comment by multicode** [comment]
Yup. That works like a charm !
Thanks a lot! :+1:
