### ISSUE TITLE
Position of Edit let content to edit missunderstood.

### ISSUE THREAD

**Issue by Mannshoch** [gturri/hidden#39]
![07 playground_playground - solag wiki - mozilla firefox](https://cloud.githubusercontent.com/assets/7795891/12350812/a0cc81d6-bb79-11e5-904b-2bd9fdbe3043.png)

In this case most people think they could edit "➔ Bekannte Fehler" but the Button appears for "➔ Wichtige Optionen"

I would prefer a small pencil icon net to the text.

**Comment by gturri** [comment]
The edit button is put here by Dokuwiki itself, so I'm not there's much that can be done here.

(I let the issue open because I would be glad if a CSS maven proves me wrong with a pull request)

**Comment by Mannshoch** [comment]
I'm not that god at CSS. I' know only that if you wish to overwrite  you has to write CSS folowing way:
eg: padding-top: 60px !important;

Our Admin do not allow to manipulate the theme (he afraid that he have to support it after software updates) so I could only do things with add-ons. 
I maybe need https://www.dokuwiki.org/plugin:editsections2 from  https://github.com/kazmiya/dokuwiki-plugin-editsections2

**Comment by gturri** [comment]
Closing because it seems rather related to a behavior of Dokuwiki than a behavior of this plugin.
