### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by jakubsuchybio** [gturri/hidden#47]
I tried all collapsible plugins and NONE of them are working. This one I think is closest to working.
My setup:
Windows 10 build 14393.5, Latest Opera, JavaScript enabled
My server:
DokuWiki Release 2016-06-26a "Elenor of Tsort", hidden plugin installed without any issue

This is my testing page:
Source:
```
====== Testing ======
<hidden>Hidden text</hidden>
<hiddenSwitch>
```
Rendered:
![](http://i.imgur.com/pBpJCDe.png)
Source of the rendered page:
```
<div class="hiddenGlobal  hiddenActive"><div class="hiddenElements"></div><div class="hiddenHead  hiddenSinceBeginning"><div class="hiddenOnHidden">
<p>
Click to display ⇲
</p>
</div><div class="hiddenOnVisible">
<p>
Click to hide ⇱
</p>
</div></div> <!-- .hiddenHead --><div class="hiddenBody">
<p>
Hidden text
</p>
</div></div><button class="button hiddenSwitch">Click to display/hide all elements</button>
```

I tried different browsers (latest Edge, latest Firefox) and it doesn't collapse on any of them.
I also tried to delete cache of that page via ```?purge=true``` in address bar. Still nothing.
I also tried to delete cache of all pages via touching ```root_dir/conf/local.php```. Still nothing.

Any ideas what could be wrong? :/
Thanks

**Comment by gturri** [comment]
Since you deleted the caches of DW and of your browser, I bet another plugin or a template is breaking the javascript. To confirm this you can either try to use your browser devtools, or switch back to the default template and deactivate all the other plugins (and delete again the caches afterwards).
See https://www.dokuwiki.org/plugin:hidden#reporting_a_bug for more info

**Comment by jakubsuchybio** [comment]
Ok so, tried to disable all extensions. Didn't help.
Then tried to set template to default and it works.
I also tried to enable all extensions with default template and it still works.

I am using a little bit customized ```vector``` template, any known incompatibilities with it?

**Comment by gturri** [comment]
I'm glad you found the issue.
I don't know this template you're using.  But this you're saying it breaks all the plugins you tried, I think it's not just an incompatibility, but it's rather breaking the javascript (just a wild guess).
To know more, you may use your browser devtool, or get in touch with the maintainer of this template
