### ISSUE TITLE
Need to allow markup that includes plugin content

### ISSUE THREAD

**Issue by Fran-B** [gturri/hidden#52]
I went through the trouble to create a well-crafted table using HTML that is easily rendered via the HTML plugin.
I then wanted to wrap that in a hide-able section because is would be wanted in printed content, and is absolutely needed by readers, but detracts from casual reading of the explanatory content.  Actually it is a parts list for the project.

Clearly the HTML plugin is not being triggered by this plugin.

Is there a way to assume the content is static, render the page with the section "not hidden", then hide the content?

**Comment by gturri** [comment]
I'm not able to reproduce this issue: the following dokuwiki page is actually displaying a table inside a hidden section:

```
<hidden>
^a^b^
|d|e|
</hidden>
```

I would be grateful if you can provide me with a snippet of dokuwiki markup which triggers the issue.
Alternatively it would also help if you can give me access to a page which shows this issue.

**Comment by Fran-B** [comment]
You clearly missed the fact that I used an HTML table, not markup.  Try
<html>
<table>
<tr><td>r1</td><td>d1</td></tr>
<tr><td>r2</td><td>d2</td></tr>
</table>
</html>

I hope that is proper XHTML, I didn't validate it.

Clearly that can be easily accomplished with simple markup.
What I actually have is an HTML table with CSS styling much too complex for simple markup.  My table was validated as displaying correctly before I wrapped it in "hidden" tags.

What I get in the hidden section is the HTML text rather than a properly rendered table.

Fran

**Comment by Fran-B** [comment]
Sorry for wasting your time.  I will create a piece of markup that reproduces it and resubmit properly; unless I too have trouble reproducing it.

Thank you for trying ay way.
Fran

**Comment by gturri** [comment]
_Closing this issue because I haven't been able to reproduce it and because it has been inactive for more than 6 months_
