### ISSUE TITLE
onHidden/onVisible are double-escaped for HTML entities

### ISSUE THREAD

**Issue by Celti** [gturri/hidden#57]
When using text that contains entities that should be escaped for the display text of the hidden tag, such as an ampersand (e.g. `<hidden Show & Tell!>`), the rendered output is double-escaped; e.g., it becomes `Show &amp;amp; Tell!`.

I *believe* this is because the calls to `p_render` on L181-182 of syntax.php result in escaping *as well as* the calls to `htmlspecialchars` on L144-145, but I'm not certain.

In any case, removing the two specific calls to `htmlspecialchars` resolved the issue for my purposes and does not appear to have introduced any new rendering or security errors, but I am not familiar enough with dokuwiki's internals to be certain.

**Comment by gturri** [comment]
Thanks a lot for this bug report and for coming up with the fix! :+1:
