### ISSUE TITLE
Suggestion: add -alwayshidden

### ISSUE THREAD

**Issue by lizat** [gturri/hidden#58]
Sorry to make a suggestion on the bugtracker, I couldn't find a discussion page for the plugin.

It would be good to add another parameter so the text would alwasy stay hideen and could be used for commenting.

Thank you for a great plugin!

liz

**Comment by gturri** [comment]
I'm not sure I completely understand: what do you mean by "always stay hidden"? Do you mean that clicking on the block, it wouldn't unfold, and that the hidden text would hence remain unreadable?

**Comment by gturri** [comment]
Closing this issue since I got no reply for almost 9 months. (Feel free to re-open it if you're still interested in this feature)
