### ISSUE TITLE
Plugin does not update

### ISSUE THREAD

**Issue by Karsten75** [gturri/hidden#61]
I tried updating it, it keeps saying that the update was still available. 

![image](https://user-images.githubusercontent.com/22965021/207633488-1a8d0b4d-1850-4f97-ace3-38d67d86b9ec.png)

I uninstalled it, and re-installed it, the message persists. 

![image](https://user-images.githubusercontent.com/22965021/207633267-9f595e18-898b-4355-a1d0-ae00feba6e84.png)

Is this perhaps an issue with the data in the plugin?

When I download the plugin zip straight from here: https://www.dokuwiki.org/plugin:hidden?s[]=guillaume&s[]=turri, I get what is on the server currently.  And that plugin info file still shows 2019-03-31 in it.  All of the files have timestamps of Dec 4, 2022, though.

**Comment by gturri** [comment]
Thanks for reporting this issue!

Indeed, I forgot to update the version here. It should be fixed now (with the commit 3c96c2e4d3606a6bc94e46f9d7d34493008ba7da I just did); one last update should be all you need.

Sorry for the inconvenience.
